# Generated by Django 4.1 on 2022-08-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='plan_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
